application: obytest
version: 1
runtime: go
api_version: go1

handlers:
- url: /_ah/login_required
  script: openIdHandler.go

- url: /openIdLogin
  script: openIdLogin.go

- url: /.*
  script: _go_app
